[build]
  command = "python --version && npm run build"
  publish = "dist" # or "out", "build", depending on your framework

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
